[package]
name = "lev"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
futures = "0.1"
rusoto_core = "0.40"
rusoto_lambda = "0.40"
structopt = "0.2"
tokio = "0.1"